---
name: Build Fedora ISO

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Get version"
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${{ github.event.head_commit.message }} | sed 's/ \[rel\]//')

      - name: "Build Fedora ISO"
        run: |
          docker run \
            --privileged \
            --rm \
            -t \
            -v "$(pwd)":/repo \
            fedora:36 \
            /bin/bash -c 'cd /repo && ./build.sh'

      - name: "Tags"
        id: tag
        run: |
          count=$(git rev-list --count HEAD)
          hash=$(git rev-parse --short HEAD)
          echo "::set-output name=tag::r${count}.${hash}"

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: t2linux-fedora-iso-${{ steps.get_version.outputs.VERSION }}
          path: ./output/*

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[rel]') }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./output/*
          tag_name: ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Nightly
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./output/*
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
