---
name: Build Fedora ISO

on:
  workflow_dispatch:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Increase Disk Space"
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /home/linuxbrew

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Build Fedora ISO"
        run: |
          docker run \
            --privileged \
            --rm \
            -t \
            -v "$(pwd)":/repo \
            fedora:37 \
            /bin/bash -c 'cd /repo && ./build.sh'

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: t2linux-fedora-iso
          path: ./output/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Nightly
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./output/*
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
